[package]
name = "soa"
version = "0.1.0"
authors = ["btsyrendylykov <bator.tsyrendylykov@lazada.com>"]

[dependencies]
futures = "0.1.17"
etcd = "0.8.0"
tokio-core = "0.1.10"
hyper = "0.11.8"
reqwest = "0.8.4"
